### ISSUE TITLE
Global document always being defined

### ISSUE THREAD

**Issue by BeeMargarida** [hivesolutions/js_util#5]
The `global.document` is always being defined, even in environments without `window`:
https://github.com/hivesolutions/js_util/blob/2276f5193d6aefaf15cd37ec427c9be3e5653b65/lib/general/mobile.js#L28

This causes problems when using both this library and `sinon`, for example, where it checks if the `document` is defined to know if it needs to create DOM elements when creating the sandbox. It should not be an empty object but `undefined`.

**Comment by BeeMargarida** [comment]
@gcandal @joamag The issue we talked yesterday that is creating problems with mocking using `sinon`.

**Comment by gcandal** [comment]
@joamag regardless of this being a problem for us or not (which depends on whether we'll want to use `sinon` for mocking), I believe `document` should only be defined if `window` also is, can't see a strong reason to act otherwise.

**Comment by joamag** [comment]
Closing this one, this may very well be considered a problem with sinon. As @gcandal we still need to even decide if we're going to use it.

**Comment by joamag** [comment]
> @joamag regardless of this being a problem for us or not (which depends on whether we'll want to use `sinon` for mocking), I believe `document` should only be defined if `window` also is, can't see a strong reason to act otherwise.

Defining a new context named document should not create side-effects, anyway this whole environment detection based on the existence of variables is always tricky. Let's focus ourselves first on discussing the need for an external library for mocking and then maybe get back to this.
